import { groq } from 'next-sanity';
import Head from 'next/head';
import React from 'react';

import { getClient } from '@/utils/sanity/client';

const query = groq`*[_type=="home"][0]`;

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Starter for Next App</h1>
      </main>
    </div>
  );
}

export async function getStaticProps({ params = {}, preview = false }) {
  const productsData = await getClient(preview).fetch(query);
  return {
    props: {
      productsData,
    },
  };
}
